web:
  build: ./web
  ports:
    - "5000:5000"
  links:
    - db
  volumes:
    - ./web:/wiki
  command: "python -u web.py"
  
bot:
  build: ./web
  ports:
    - "6000:6000"
  links:
    - db
  volumes:
    - ./web:/wiki
  command: "python -u runbot.py"

db:
  image: mongo:latest
  
# if we want to balanced
#nginx:
#  restart: "always"
#  build: ./nginx/
#  ports:
#    - "80:80"
#  volumes:
#    - /www/static
#  volumes_from:
#    - web
#  links:
#    - web:web
